name: Go

on: [push, pull_request]


jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'


      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Test with the Go CLI
        run: go test ./... -v
